#+title: org-change: Track changes in org-mode
#+author: Stefano Ghirlanda
#+email: drghirlanda@gmail.com
#+options: toc:nil ':t
#+latex_header: \hypersetup{hidelinks}

* Introduction

org-change is a minor mode that (ab)uses the org-mode link syntax for
a simple "track changes" feature similar to some word processors.

org-change provides:
- A ~change~ link type to mark additions, deletions, and replacements.
- Functions and key bindings to manipulate ~change~ links.
- Export filters to render ~change~ links (currently Latex and HTML).

* Installation

Install manually from here for now, hopefully from MELPA soon.

* ~change~ link syntax

To indicate that "old text" is being replaced by "new text," the
~change~ link syntax is:
#+begin_src org
  [[change:old text][new text]]
#+end_src
The idea is that you end up seeing only "new text," because org-mode
(typically) hides the part of the link within the first pair of
brackets. To indicate an addition, just omit ~old text~:
#+begin_src org
  [[change:][new text]]
#+end_src
To indicate a deletion, use ~((DELETED))~ as ~new text~:
#+begin_src org
  [[change:old text][((DELETED))]]
#+end_src
You can also embed comments in change links by surrounding them with
double stars at the end of ~new text~:
#+begin_src org
  [[change:old text][new text**A comment**]]
#+end_src
All this by itself is not very useful, but read on.

* ~change~ link manipulation

org-change provides key sequences to easily insert and manipulate
change links. All key sequences start with ~C-`~ (control + left
quote). Not the prettiest, but, Emacs having been around for a while,
few control prefixes are free. It's the curse of keymensionality. It
can be [[Customization][customized]].

You can mark additions, deletions, and replacements like this:
- ~C-` a~ :: for additions.
- ~C-` d~ :: for deletions.
- ~C-` r~ :: for replacements.
These actions operate on the active region. For example, in the case
of replacement, the selected text is marked for deletion, and you are
prompted for new text. You can also use ~C-` a~ without marking a
region, in which case you are prompted for new text.

Key sequences are also provided to accept and reject the change under the cursor:
- ~C-` k~ :: to accept.
- ~C-` x~ :: to reject.
"Accept" means to delete the change link (including any comments) and
insert the new text (or nothing, if the change is a
deletion). "Reject" means to delete the change link and insert the old
text (or nothing, if the change is an addition).

The following functionality is provided by org-mode, and is useful for
~change~ links:
- ~C-c C-l~ :: lets you edit the link in the minibuffer. Because this
  is an org-mode function for all links, it will display the "old
  text" as =Link: change:old text= and the "new text" as =Description: new text=.
- ~M-x org-toggle-link-display~ :: toggles between showing and hiding
  the hidden part of every link in the buffer. This can be useful to
  work on longer edits.

* Exporting
** LaTeX export

When exporting to LaTeX, org-change uses the ~changes~ package, which
must be included with a ~#+latex_header~ line:
#+begin_src org
  #+latex_header: \usepackage{changes}
#+end_src
org-change will then use the commands ~\added~, ~\deleted~, and
~\replaced~ provided by this package.

The content of the change link can contain org-mode notation like
*bold* and /emphasis/, as well as Latex commands. However, some other
features do not currently work. Notably org-ref links must be
translated manually to Latex. So this will *not* work:
#+begin_src org
  [[change:][Let's cite something cite:something]]
#+end_src
But this will:
#+begin_src org
  [[change:][Let's cite something \cite{something}]]
#+end_src

org-change supports some additional features of the ~changes~
package. First, it supports comments, so that
#+begin_src org
  [[change:old text][new text**A comment**]]
#+end_src
is exported to
#+begin_src org
  \replaced[comment=A comment]{new text}{old text}
#+end_src
You can also sneak in other fields supported by ~changes~ at the end
of the comment. For example, you can indicate the author of the
comment:
#+begin_src org
  [[change:old text][new text**My comment,author=SG**]]
#+end_src
which is exported to:
#+begin_src org
  \replaced[comment=My comment,author=SG]{new text}{old text}
#+end_src

** HTML export

When exporting to HTML, org-change produces ~<span>~ elements with
classes ~org-change-added~, ~org-change-deleted~, and
~org-change-comment~. A replace link has both an added and a deleted
span, while add and delete links only have one span. The comment span
is embedded in the add span when present, otherwise in the delete
span. So this:
#+begin_src org
  [[change:old text][new-text**comment**]]
#+end_src
becomes this:
#+begin_example
<span class="org-change-added">new text<span class="org-change-comment">comment</span></span><span class="org-change-deleted">old text</span>
#+end_example
You can then use CSS to display these classes as desired.

The example above is generated with:
#+name: html-example
#+begin_src elisp
  (org-change--export-html "old text" "new text" "comment")
#+end_src
which happens automatically when exporting.

* Customizing and extending
** Customization

The key sequences and the face used to display change links can be
changed through the customize interface:
#+begin_src org
  M-x customize-group RET org-change
#+end_src

** Adding exporters

To add an export format, add something like this to your org file:
#+begin_src org
  ,#+begin_src elisp
    (org-change-add-export-backend 'backend 'backend-function)
  ,#+end_src
#+end_src
where ~backend~ is a backend known to org-mode and ~backend-function~
is a function that produces the desired string from three string
arguments: ~old-text~, ~new-text~, and ~comment~.

* Bugs and limitations

- org-ref links inside ~change~ links are not interpreted.
- Link hiding is sometimes inaccurate in org-mode. You may see stray
  brackets especially with link that span multiple lines. Often ~M-q~
  takes care of this.

* Planned features

- More export filters
- A function ~org-change-accept-all~ to process all change links in the
  buffer
- Make it possible to select final or draft when exporting. Final just
  uses new text.
- A function to manipulate comment.
  
* Notes

To get started on org-change, I described some features to ChatGPT
(April 2023 version) and asked for the corresponding code. It was
wrong in many ways, like using non-existing functions with plausible
names (~org-escape-latex~), oscillating between a single- and a
multi-file package, and just not doing what it was supposed to do. It
would also insist that some things would work even when told that they
did not. It did have a good general grasp of many things, like
defining a minor mode and customize variables, and it was always
syntactically correct.
